final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


urlpatterns = [
    path('home/', include('home.urls')),
    path('members/', include('members.urls')),
    path('products/', include('products.urls')),
    path('tx/', include('tx.urls')),
    path('admin/', admin.site.urls),
    path('option/', include('option.urls')),
    path('stock_backtesting/', include('stock_backtesting.urls')),
    path('', views.home)
]

home/urls.py
from django.urls import path, include
from home import views


app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

option/urls.py
from django.urls import path, include
from option import views

app_name = 'option'
urlpatterns = [
    path('', views.option, name='option_home'),
]

products/urls.py
from django.urls import path, include
from products import views

app_name = 'products'
urlpatterns = [
    path('', views.products, name='products_home'),
]

stock_backtesting/urls.py
from django.urls import path, include
from stock_backtesting import views

app_name = 'stock_backtesting'
urlpatterns = [
    path('', views.stock_backtesting, name='stock_backtesting_home'),
]

tx/urls.py
from django.urls import path, include
from tx import views

app_name = 'tx'
urlpatterns = [
    path('', views.tx, name='tx_home'),
]

templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>台股小幫手</title>
        {% block extra_head %}{% endblock %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <body>
      <!-- <div class="container"> -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
          <!-- <img src="https://live.staticflickr.com/3595/3475465970_7044242629.jpg" width="80" height="30" alt="" loading="lazy"> -->
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home:home' %}">首頁<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'products:products_home' %}">個股分析</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'stock_backtesting:stock_backtesting_home' %}">投組回測</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'tx:tx_home' %}">台指期分析</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'option:option_home' %}">台指選分析</a>
            </li>
          </ul>
        </div>
      </nav>
      <!-- </div> -->
      <!-- <div class='container'> -->
        {% block body_block %}
        {% endblock %}
      <!-- </div> -->
    </body>
</html>